version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres-quartz-example
    environment:
      POSTGRES_DB: quartz-example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
volumes:
  postgres-data:

